/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.	*/



@interface NSTokenAttachment : NSTextAttachment
{
    id _delegate;
}

- initWithDelegate:fp8;
- (void)encodeWithCoder:fp8;
- initWithCoder:fp8;
- attachmentCell;
- delegate;
- (void)setDelegate:fp8;

@end

