
#ifndef AtoZ_AtoZCategories_h
#define AtoZ_AtoZCategories_h


/* COCOA CATEGORIES	*/ /* FOUNDATION  CATEGORIES */

#import "CAAnimation+AtoZ.h"
#import "CALayer+AtoZ.h"
#import "CAShapeLayer+AtoZ.h"
#import "CoreData+AtoZ.h"
#import "KSHTMLWriter+AtoZ.h"
#import "NSApplication+AtoZ.h"
#import "NSArray+AtoZ.h"
#import "NSArray+F.h"
#import "NSBezierPath+AtoZ.h"
#import "NSBundle+AtoZ.h"
#import "NSCell+AtoZ.h"
#import "NSColor+AtoZ.h"
#import "NSDate+AtoZ.h"
#import "NSDictionary+AtoZ.h"
#import "NSError+AtoZ.h"
#import "NSEvent+AtoZ.h"
#import "NSFileManager+AtoZ.h"
#import "NSFont+AtoZ.h"
#import "NSImage+AtoZ.h"
#import "NSImage-Tint.h"
#import "NSIndexSet+AtoZ.h"
#import "NSNotificationCenter+AtoZ.h"
#import "NSNumber+AtoZ.h"
#import "NSNumber+F.h"
#import "NSObject+AtoZ.h"
#import "NSObject+Properties.h"
#import "NSObject+StrictProtocols.h"
#import "NSObject-Utilities.h"
#import "NSOutlineView+AtoZ.h"
#import "NSScreen+AtoZ.h"
#import "NSShadow+AtoZ.h"
#import "NSSplitView+DMAdditions.h"
#import "NSString+AtoZ.h"
#import "NSString+AtoZEnums.h"
#import "NSTableView+AtoZ.h"
#import "NSTask+OneLineTasksWithOutput.h"
#import "NSTextView+AtoZ.h"
#import "NSTextView+SyntaxColoring.h"
#import "NSThread+AtoZ.h"
#import "NSURL+AtoZ.h"
#import "NSUserDefaults+Subscript.h"
#import "NSValue+AtoZ.h"
#import "NSValueTransformer+TransformerKit.h"
#import "NSView+AtoZ.h"
#import "NSWindow+AtoZ.h"
#import "TUIView+Dimensions.h"
#import "WebView+AtoZ.h"

#import "NSDictionary+F.h"
#import "NSHTTPCookie+Testing.h"
#import "BaseModel+AtoZ.h"

//#import "NSManagedObjectContext+EasyFetch.h"
//#import "NSUserDefaults+AtoZ.h"


#import "BlocksAdditions.h"
#import "AddressBookImageLoader.h"
#import "AFNetworking.h"
#import "AGNSSplitView.h"
#import "AGNSSplitViewDelegate.h"
#import "AHLayout.h"
#import "ASIHTTPRequest.h"
#import "BBMeshView.h"
#import "BETaskHelper.h"
#import "BlockDelegate.h"
#import "AtoZSwizzles.h"

//#import "ConciseKit.h"
#import "CPAccelerationTimer.h"
#import "CTBadge.h"
#import "CTGradient.h"
#import "DSObjectiveCSyntaxDefinition.h"
#import "DSPodfileSyntaxDefinition.h"
#import "DSPodspecSyntaxDefinition.h"
#import "DSRubySyntaxDefinition.h"
#import "DSSyntaxCollection.h"
#import "DSSyntaxHighlighter.h"
#import "DSSyntaxTextView.h"
#import "iCarousel.h"
#import "JSONKit.h"
#import "KGNoise.h"
#import "LoremIpsum.h"
#import "MAAttachedWindow.h"
#import "MAKVONotificationCenter.h"
#import "MASShortcut.h"  // SHortcut Manager and View
#import "NotificationCenterSpy.h"
#import "NSBag.h"
#import "NSMenu+Dark.h" 
#import "NSObject_KVOBlock.h"
#import "M13OrderedDictionary.h"
//  #import "NSTerminal.h"
#import "NSWindow_Flipr.h"
#import "NullSafe.h"
#import "ObjectMatcher.h"
#import "PXListDocumentView.h"
#import "PXListView.h"
#import "PXListViewCell.h"
#import "RuntimeReporter.h"
#import "SDToolkit.h"
#import "SelectorMatcher.h"
#import "SIAppCookieJar.h"
#import "SIAuthController.h"
#import "SIConstants.h"
#import "SIInboxDownloader.h"
#import "SIInboxModel.h"
#import "SIViewControllers.h"
#import "SIWindow.h"
#import "StandardPaths.h"
#import "StarLayer.h"
#import "StickyNoteView.h"
#import "Transition.h"
#import "TransparentWindow.h"
#import "TUIFastIndexPath.h"
#import "XLDragDropView.h"
//#import "AtoZMacroDefines.h"
//#import "AtoZUmbrella.h"
//#import "AtoZTypes.h"
//#import "AtoZGeometry.h"
#import "AtoZFunctions.h"
#import "AZLog.h"
#import "AZProxy.h"
#import "AZBaseModel.h"  // NSDocument / AZDoc
#import "SynthesizeSingleton.h"
#import "AZObserversAndBinders.h"
#import "MondoSwitch.h"
#import "AssetCollection.h"
#import "AtoZColorWell.h"
#import "AtoZContacts.h"
#import "AtoZDelegate.h"
#import "AtoZGridView.h"
#import "AtoZGridViewProtocols.h"
#import "AtoZInfinity.h"
#import "AtoZModels.h"
//#import "AtoZNodeProtocol.h"
#import "AtoZWebSnapper.h"
#import "AZApplePrivate.h"
#import "AZASIMGV.h"
#import "AZAttachedWindow.h"
#import "AZAXAuthorization.h"
#import "AZBackground.h"
#import "AZBackgroundProgressBar.h"
#import "AZBlockView.h"
#import "AZBonjourBlock.h"
#import "AZBorderlessResizeWindow.h"
#import "AZBox.h"
#import "AZBoxGrid.h"
#import "AZBoxMagic.h"
#import "AZCalculatorController.h"
#import "AZCLI.h"
#import "AZCLICategories.h"
#import "AZColor.h"
#import "AZCoreScrollView.h"
#import "AZDebugLayer.h"
#import "AZDockQuery.h"
#import "AZExpandableView.h"
#import "AZFacebookConnection.h"
#import "AZFactoryView.h"
#import "AZFavIconManager.h"
#import "AZFoamView.h"
#import "AZGit.h"
#import "AZGoogleImages.h"
#import "AZGrid.h"
#import "AZHomeBrew.h"
#import "AZHostView.h"
#import "AZHTMLParser.h"
#import "AZHTTPURLProtocol.h"
#import "AZImageToDataTransformer.h"
#import "AZIndeterminateIndicator.h"
#import "AZIndexedObjects.h"
#import "AZInfiniteCell.h"
#import "AZInstantApp.h"
#import "AZLassoView.h"
#import "AZLaunchServices.h"
#import "AZLayer.h"
#import "AZLogConsole.h"
#import "AZMacTrackBall.h"
#import "AZMedallionView.h"
#import "AZMouser.h"
#import "AZObject.h"
#import "AZPopupWindow.h"
#import "AZPrismView.h"
#import "AZProcess.h"
#import "AZProgressIndicator.h"
#import "AZPropellerView.h"
#import "AZProportionalSegmentController.h"
#import "AZQueue.h"
#import "AZScrollerLayer.h"
#import "AZScrollPaneLayer.h"
#import "AZSegmentedRect.h"
#import "AZSemiResponderWindow.h"
#import "AZSimpleView.h"
#import "AZSizer.h"
#import "AZSnapShotLayer.h"

#import "SoundManager.h"
#import "AZSound.h"
#import "AZSourceList.h"
#import "AZSpeechRecognition.h"
#import "AZSpinnerLayer.h"
#import "AZStopwatch.h"
#import "AZSyntaxTheme.h"
#import "AZSynthesize.h"
#import "AZTalker.h"
#import "AZTimeLineLayout.h"
#import "AZToggleArrayView.h"
#import "AZTrackingWindow.h"
//  #import "AZURLSnapshot.h"
#import "AZVeil.h"
#import "AZWeakCollections.h"
#import "AZWindowExtend.h"
#import "AZWindowTab.h"
#import "AZXMLWriter.h"
#import "NSOperationStack.h"
#import "Bootstrap.h"
#import "CalcModel.h"
#import "CAScrollView.h"
#import "CAWindow.h"
#import "DefinitionController.h"
#import "HTMLNode.h"
#import "IsometricView.h"
#import "LetterView.h"
#import "NSTextView+SyntaxColoring.h"
#import <AtoZ/AtoZEmoji.h>
#import "AZNamedColors.h"

#ifndef IMPORTMODULEHEADERSBECAUSEITWANTSTO
#define IMPORTMODULEHEADERSBECAUSEITWANTSTO
// <module-includes>:1:1: warning: umbrella header for module 'AtoZ' does not include header 'ASIDownloadCache.h' [-Wincomplete-umbrella]
#import "ASIDataDecompressor.h"
#import "ASIDownloadCache.h"
#import "ASIFormDataRequest.h"
#import "ASIInputStream.h"
#import "ASINetworkQueue.h"
#import "AtoZStack.h"
#import "AtoZWebSnapperGridViewController.h"
#import "AZBeetlejuice.h"
#import "AZButton.h"
#import "AZCSSColorExtraction.h"
#import "AZHoverButton.h"
#import "AZMatteButton.h"
#import "AZMatteFocusedGradientBox.h"
#import "AZMattePopUpButton.h"
#import "AZMattePopUpButtonView.h"
#import "AZMatteSegmentedControl.h"
#import "AZURLBar.h"
#import "AZWikipedia.h"
#import "AZWindowTabViewController.h"
#import "DSURLDataSource.h"
#import "EGOCache.h"
#import "EGOImageLoadConnection.h"
#import "GTMHTTPFetcher.h"
#import "GTMNSString+HTML.h"
#import "HTMLParserViewController.h"
#import "MediaServer.h"
#import "NSColor+RGBHex.h"
#import "NSObject+AZBlockObservation.h"
#import "NSString+SymlinksAndAliases.h"
#import "NSString+PathAdditions.h"
#import "NSTerminal.h"
#import "OperationsRunnerProtocol.h"
#import "PythonOperation.h"
#import "RoundedView.h"
#import "SDCloseButtonCell.h"
#import "TUITableView+Updating.h"

#endif /* IMPORTMODULEHEADERSBECAUSEITWANTSTO */

//  #ifdef DEBUG
//    static const int ddLogLevel = LOG_LEVEL_VERBOSE;
//  #else
//    static const int ddLogLevel = LOG_LEVEL_WARN;
//  #endif

/*	INACTIVE
#import "AZLassoLayer.h"
*/

/*	COLOR AND IMAGE CLASSES */
/*  FACEBOOK	*/
/* CONTROLS */
/* CoreScroll */
/* ESSENTIAL */
/* FOUNDATION CLASSES */
/* MODEL */
/* old home of umbrellas */
/* STACKEXCHANGE */
/* WINDOWS */
//	#import "AtoZModels.h"
//	#import "AZFile.h"
//	#import "AZPalette.h"
//   CORE
// COREDATA
// END CORE
// TwUI
// UNUSED
// Views
//#import "AZBoxLayer.h"
//#import "azCarousel.h"
#import "AZDarkButtonCell.h"
#import "ASIDataCompressor.h"

//#import "AZFileGridView.h"
//#import "AZHTTPRouter.h"
//#import "AZMatteButton.h"
//#import "AZMatteFocusedGradientBox.h"
//#import "AZMattePopUpButton.h"
//#import "AZMattePopUpButtonView.h"
//#import "AZMatteSegmentedControl.h"
//#import "AZNotificationCenter.h"
//#import "AZOverlay.h"
//#import "AZToggleView.h"
//#import "CKSingleton.h"
//#import "CTBlockDescription.h"  in autobox now
//#import "DSURLDataSource.h"
//#import "MondoSwitch.h"
//#import "PythonOperation.h"
//#import "SNRHUDButtonCell.h"
//#import "SNRHUDScrollView.h"
//#import "SNRHUDSegmentedCell.h"
//#import "SNRHUDTextFieldCell.h"
//#import "SNRHUDTextView.h"
//#import "SNRHUDWindow.h"
//#import "TUICarouselNavigationController.h"
//#import "TUINavigationController.h"
//#import "TUIRefreshControl.h"
//#import "TUITableOulineView.h"
//#import <AtoZ
//#import <AtoZUI/AtoZUI.h>
//#import <MapKit/MapKit.h>
//#import <NanoStore/NanoStore.h>
//#import <RMKit/RMKit.h>
//#import <XPCKit/XPCKit.h>
//#import <Zangetsu/Zangetsu.h>
////#import "AZStatusItemView.h"
////#import "SNRHUDImageCell.h"
////#import "SNRHUDKit.h"
//Classes


#endif /* AtoZ_AtoZCategories_h */